-- Add a generic video_url field to appointments for any video call link
-- (Google Meet, Zoom manual, Whereby, Teams, etc.)
-- Separate from zoom_join_url which is auto-generated by Zoom OAuth integration.

alter table appointments
  add column if not exists video_url text default null;
